// AUTO-GENERATED by scripts/generate-site-index.ts. Do not edit.
// Run `pnpm prebuild` or any build to regenerate.

export interface SitePage {
  href: string
  title: string
  description: string
  keywords: string
  group: string
}

export const SITE_PAGES: SitePage[] = [
  {
    "href": "/about",
    "title": "About",
    "description": "What CredStack is, why it exists, and who builds it.",
    "keywords": "about what credstack is, why it exists, and who builds it.  about",
    "group": "About"
  },
  {
    "href": "/advisor",
    "title": "Advisor",
    "description": "",
    "keywords": "advisor   advisor",
    "group": "AI tools"
  },
  {
    "href": "/analyzer",
    "title": "Analyzer",
    "description": "",
    "keywords": "analyzer   analyzer",
    "group": "AI tools"
  },
  {
    "href": "/apply/documents",
    "title": "Credit Card Application Documents",
    "description": "Complete document checklist for applying for a credit card in India. Salaried, self-employed, student and NRI requirements. Bank-specific notes included.",
    "keywords": "credit card application documents complete document checklist for applying for a credit card in india. salaried, self-employed, student and nri requirements. bank-specific notes included.  apply documents",
    "group": "Apply"
  },
  {
    "href": "/banks",
    "title": "Banks",
    "description": "Browse credit, debit, and prepaid cards by issuer.",
    "keywords": "banks browse credit, debit, and prepaid cards by issuer.  banks",
    "group": "Cards"
  },
  {
    "href": "/blog",
    "title": "Blog",
    "description": "Long-form writing on Indian credit cards, rewards strategy, and product updates.",
    "keywords": "blog long-form writing on indian credit cards, rewards strategy, and product updates.  blog",
    "group": "Company"
  },
  {
    "href": "/cards",
    "title": "Cards",
    "description": "",
    "keywords": "cards   cards",
    "group": "Cards"
  },
  {
    "href": "/careers",
    "title": "Careers",
    "description": "Work on CredStack.",
    "keywords": "careers work on credstack.  careers",
    "group": "Company"
  },
  {
    "href": "/compare",
    "title": "Compare",
    "description": "",
    "keywords": "compare   compare",
    "group": "Cards"
  },
  {
    "href": "/contact",
    "title": "Contact",
    "description": "How to reach CredStack for support, partnerships, security disclosures, or feedback.",
    "keywords": "contact how to reach credstack for support, partnerships, security disclosures, or feedback.  contact",
    "group": "Support"
  },
  {
    "href": "/cookies",
    "title": "Cookie Policy",
    "description": "How CredStack uses cookies and similar technologies.",
    "keywords": "cookie policy how credstack uses cookies and similar technologies.  cookies",
    "group": "Legal"
  },
  {
    "href": "/disclaimer",
    "title": "Disclaimer",
    "description": "Important disclosures about CredStack and the information it provides.",
    "keywords": "disclaimer important disclosures about credstack and the information it provides.  disclaimer",
    "group": "Legal"
  },
  {
    "href": "/docs",
    "title": "API Docs",
    "description": "Programmatic access to CredStack data.",
    "keywords": "api docs programmatic access to credstack data.  docs",
    "group": "Support"
  },
  {
    "href": "/eligibility",
    "title": "Eligibility",
    "description": "",
    "keywords": "eligibility   eligibility",
    "group": "AI tools"
  },
  {
    "href": "/faq",
    "title": "FAQ",
    "description": "Frequently asked questions about CredStack.",
    "keywords": "faq frequently asked questions about credstack.  faq",
    "group": "Support"
  },
  {
    "href": "/help",
    "title": "Help Center",
    "description": "Guides and articles for getting the most out of CredStack.",
    "keywords": "help center guides and articles for getting the most out of credstack.  help",
    "group": "Support"
  },
  {
    "href": "/learn",
    "title": "Credit Academy",
    "description": "Plain-English explanations of how credit cards, CIBIL scores, reward programmes, and forex markup actually work in India.",
    "keywords": "credit academy plain-english explanations of how credit cards, cibil scores, reward programmes, and forex markup actually work in india.  learn",
    "group": "Learn"
  },
  {
    "href": "/learn/first-credit-card",
    "title": "Best First Credit Card in India 2026",
    "description": "A complete guide to picking your first credit card in India. Eligibility, recommended starter cards, what to expect, and rookie mistakes to avoid.",
    "keywords": "best first credit card in india 2026 a complete guide to picking your first credit card in india. eligibility, recommended starter cards, what to expect, and rookie mistakes to avoid.  learn first credit card",
    "group": "Learn"
  },
  {
    "href": "/learn/rewards",
    "title": "Credit Card Rewards Programmes",
    "description": "How HDFC RPs, Amex MR, ICICI RPs, SBI RPs, Axis EDGE, Tata NeuCoins, 6E Rewards, and Maharaja Club really work. Earn rates, redemption ladders, transfer partners.",
    "keywords": "credit card rewards programmes how hdfc rps, amex mr, icici rps, sbi rps, axis edge, tata neucoins, 6e rewards, and maharaja club really work. earn rates, redemption ladders, transfer partners.  learn rewards",
    "group": "Learn"
  },
  {
    "href": "/methodology",
    "title": "Methodology",
    "description": "How CredStack verifies card data, computes net annual value, and uses AI to generate recommendations.",
    "keywords": "methodology how credstack verifies card data, computes net annual value, and uses ai to generate recommendations.  methodology",
    "group": "About"
  },
  {
    "href": "/offers",
    "title": "Card Offers",
    "description": "Live credit-card offers across Indian merchants — scraped weekly from bank hubs and aggregator sites, organised by category and merchant.",
    "keywords": "card offers live credit-card offers across indian merchants — scraped weekly from bank hubs and aggregator sites, organised by category and merchant.  offers",
    "group": "Rewards"
  },
  {
    "href": "/optimizer",
    "title": "Optimizer",
    "description": "",
    "keywords": "optimizer   optimizer",
    "group": "AI tools"
  },
  {
    "href": "/page.tsx",
    "title": "Page.tsx",
    "description": "",
    "keywords": "page.tsx   page.tsx",
    "group": "Pages"
  },
  {
    "href": "/press",
    "title": "Press",
    "description": "Press kit, fact sheet, and media contact for CredStack.",
    "keywords": "press press kit, fact sheet, and media contact for credstack.  press",
    "group": "Company"
  },
  {
    "href": "/privacy",
    "title": "Privacy Policy",
    "description": "How CredStack collects, uses, and protects your personal information.",
    "keywords": "privacy policy how credstack collects, uses, and protects your personal information.  privacy",
    "group": "Legal"
  },
  {
    "href": "/rewards/expiry",
    "title": "Reward Expiry Tracker",
    "description": "Track when reward points and cashback on each of your cards expire.",
    "keywords": "reward expiry tracker track when reward points and cashback on each of your cards expire.  rewards expiry",
    "group": "Rewards"
  },
  {
    "href": "/safety/fraud-guide",
    "title": "Credit Card Fraud",
    "description": "Step-by-step what to do if your credit card is stolen, cloned, or fraudulently charged. RBI zero-liability rules, complaint paths, and common scam patterns.",
    "keywords": "credit card fraud step-by-step what to do if your credit card is stolen, cloned, or fraudulently charged. rbi zero-liability rules, complaint paths, and common scam patterns.  safety fraud guide",
    "group": "Safety"
  },
  {
    "href": "/safety/helplines",
    "title": "Credit Card Helplines",
    "description": "Toll-free customer service, complaint email, and escalation paths for every major Indian credit card issuer. Banking Ombudsman link for unresolved disputes.",
    "keywords": "credit card helplines toll-free customer service, complaint email, and escalation paths for every major indian credit card issuer. banking ombudsman link for unresolved disputes.  safety helplines",
    "group": "Safety"
  },
  {
    "href": "/safety/rbi-updates",
    "title": "RBI Credit Card Rule Updates",
    "description": "Plain-English summaries of RBI circulars that affect Indian credit card holders. What changed, when it takes effect, what it means for you.",
    "keywords": "rbi credit card rule updates plain-english summaries of rbi circulars that affect indian credit card holders. what changed, when it takes effect, what it means for you.  safety rbi updates",
    "group": "Safety"
  },
  {
    "href": "/safety/virtual-cards",
    "title": "Virtual Credit Cards & Tokenization",
    "description": "Which Indian credit cards support virtual cards, tokenization, and disposable card numbers. Compare security features across HDFC, SBI, ICICI, Axis, Amex.",
    "keywords": "virtual credit cards & tokenization which indian credit cards support virtual cards, tokenization, and disposable card numbers. compare security features across hdfc, sbi, icici, axis, amex.  safety virtual cards",
    "group": "Safety"
  },
  {
    "href": "/terms",
    "title": "Terms of Service",
    "description": "The rules for using CredStack.",
    "keywords": "terms of service the rules for using credstack.  terms",
    "group": "Legal"
  },
  {
    "href": "/tools/emi-calculator",
    "title": "Credit Card EMI Calculator",
    "description": "Compare no-cost EMI and interest-bearing EMI on Indian credit cards. See effective interest after processing fees and the real total cost.",
    "keywords": "credit card emi calculator compare no-cost emi and interest-bearing emi on indian credit cards. see effective interest after processing fees and the real total cost.  tools emi calculator",
    "group": "Tools"
  },
  {
    "href": "/tools/interest-calculator",
    "title": "Credit Card Interest Calculator",
    "description": "See how much you",
    "keywords": "credit card interest calculator see how much you  tools interest calculator",
    "group": "Tools"
  },
  {
    "href": "/tools/points-converter",
    "title": "Reward Points Value Calculator",
    "description": "Convert reward points to rupee value for HDFC, SBI, ICICI, Axis, Amex, IDFC. Compare statement credit vs vouchers vs airline miles redemption.",
    "keywords": "reward points value calculator convert reward points to rupee value for hdfc, sbi, icici, axis, amex, idfc. compare statement credit vs vouchers vs airline miles redemption.  tools points converter",
    "group": "Tools"
  }
]
