/**
 * Walks app/ to discover every page.tsx, pulls metadata.title + heuristic
 * keywords, and writes lib/data/site-pages.generated.ts.
 *
 * Runs as a prebuild step so the SearchCommand always reflects the current
 * route tree without any manual list to maintain.
 *
 * Excluded:
 *  - dynamic segments ([id]) — no stable URL
 *  - dashboard/* — auth-gated, indexed separately
 *  - api/* — server routes, no UI
 *  - auth/* — flow pages, not navigable
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, relative, dirname } from 'node:path'

const ROOT = join(process.cwd(), 'app')
const OUT = join(process.cwd(), 'lib', 'data', 'site-pages.generated.ts')

const EXCLUDE_PREFIXES = ['api/', 'auth/', 'dashboard/']
const EXCLUDE_DYNAMIC = /\[[^\]]+\]/

interface PageEntry {
  href: string
  title: string
  description: string
  keywords: string
  group: string
}

async function walk(dir: string, acc: string[] = []): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  for (const e of entries) {
    const full = join(dir, e.name)
    if (e.isDirectory()) await walk(full, acc)
    else if (e.isFile() && e.name === 'page.tsx') acc.push(full)
  }
  return acc
}

function hrefFromFile(file: string): string {
  const rel = relative(ROOT, file).replace(/\\/g, '/').replace(/\/page\.tsx$/, '')
  if (rel === '') return '/'
  return '/' + rel
}

function shouldExclude(href: string): boolean {
  const path = href.replace(/^\//, '')
  if (EXCLUDE_DYNAMIC.test(href)) return true
  return EXCLUDE_PREFIXES.some((p) => path === p.replace(/\/$/, '') || path.startsWith(p))
}

function deriveGroup(href: string): string {
  if (href === '/') return 'Home'
  const top = href.split('/')[1]
  const map: Record<string, string> = {
    cards: 'Cards',
    compare: 'Cards',
    banks: 'Cards',
    advisor: 'AI tools',
    analyzer: 'AI tools',
    optimizer: 'AI tools',
    eligibility: 'AI tools',
    rewards: 'Rewards',
    offers: 'Rewards',
    tools: 'Tools',
    apply: 'Apply',
    safety: 'Safety',
    learn: 'Learn',
    methodology: 'About',
    about: 'About',
    contact: 'Support',
    help: 'Support',
    faq: 'Support',
    docs: 'Support',
    careers: 'Company',
    press: 'Company',
    blog: 'Company',
    privacy: 'Legal',
    terms: 'Legal',
    cookies: 'Legal',
    disclaimer: 'Legal',
  }
  return map[top] ?? 'Pages'
}

function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function fallbackTitle(href: string): string {
  if (href === '/') return 'Home'
  const parts = href.split('/').filter(Boolean)
  return titleCase(parts[parts.length - 1])
}

const TITLE_RE = /title\s*:\s*["'`]([^"'`]+)["'`]/
const DESC_RE = /description\s*:\s*["'`]([^"'`]+)["'`]/

async function extractMeta(file: string): Promise<{ title?: string; description?: string }> {
  try {
    const src = await readFile(file, 'utf8')
    const t = TITLE_RE.exec(src)
    const d = DESC_RE.exec(src)
    return {
      title: t?.[1]?.replace(/\s*[—|-].*$/, '').trim(),
      description: d?.[1]?.trim(),
    }
  } catch {
    return {}
  }
}

async function main() {
  const files = await walk(ROOT)
  const entries: PageEntry[] = []

  for (const f of files) {
    const href = hrefFromFile(f)
    if (shouldExclude(href)) continue
    const meta = await extractMeta(f)
    const title = meta.title || fallbackTitle(href)
    const description = meta.description || ''
    const keywords = `${title} ${description} ${href.replace(/[\/-]/g, ' ')}`.toLowerCase()
    entries.push({
      href,
      title,
      description,
      keywords,
      group: deriveGroup(href),
    })
  }

  entries.sort((a, b) => a.href.localeCompare(b.href))

  const body = `// AUTO-GENERATED by scripts/generate-site-index.ts. Do not edit.
// Run \`pnpm prebuild\` or any build to regenerate.

export interface SitePage {
  href: string
  title: string
  description: string
  keywords: string
  group: string
}

export const SITE_PAGES: SitePage[] = ${JSON.stringify(entries, null, 2)}
`

  await mkdir(dirname(OUT), { recursive: true })
  await writeFile(OUT, body, 'utf8')
  console.log(`Wrote ${entries.length} pages → ${relative(process.cwd(), OUT)}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
