import type { SourceDefinition } from '@/lib/types/offers'

export const SOURCES: SourceDefinition[] = [
  // Bank hubs (Mondays, staggered hourly to spread load)
  {
    slug: 'hdfc-hub',
    name: 'HDFC Bank Card Offers',
    url: 'https://www.hdfcbank.com/personal/pay/cards/credit-cards/offers',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 6 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, waitFor: 2000, formats: ['markdown'] },
    issuerHint: 'HDFC Bank',
  },
  {
    slug: 'sbi-hub',
    name: 'SBI Card Offers',
    url: 'https://www.sbicard.com/en/personal/offers.page',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 7 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'SBI Card',
  },
  {
    slug: 'axis-hub',
    name: 'Axis Bank Offers Corner',
    url: 'https://www.axisbank.com/cards/credit-card/offers-corner',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 8 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, waitFor: 2000, formats: ['markdown'] },
    issuerHint: 'Axis Bank',
  },
  {
    slug: 'icici-hub',
    name: 'ICICI Bank Card Offers',
    url: 'https://www.icicibank.com/personal-banking/cards/credit-card/offer',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 9 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'ICICI Bank',
  },
  {
    slug: 'amex-hub',
    name: 'American Express India Offers',
    url: 'https://www.americanexpress.com/in/benefits/offers/',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 10 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, waitFor: 3000, formats: ['markdown'] },
    issuerHint: 'American Express',
  },
  {
    slug: 'idfc-hub',
    name: 'IDFC FIRST Bank Offers',
    url: 'https://www.idfcfirstbank.com/credit-card/offers',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 11 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'IDFC FIRST Bank',
  },
  {
    slug: 'indusind-hub',
    name: 'IndusInd Bank Offers',
    url: 'https://www.indusind.com/in/en/personal/cards/credit-card/offers.html',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 12 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'IndusInd Bank',
  },
  {
    slug: 'au-hub',
    name: 'AU Small Finance Bank Offers',
    url: 'https://www.aubank.in/personal-banking/credit-cards/offers',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 13 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'AU Small Finance Bank',
  },
  {
    slug: 'hsbc-hub',
    name: 'HSBC India Offers',
    url: 'https://www.hsbc.co.in/credit-cards/offers/',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 14 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'HSBC',
  },
  {
    slug: 'yes-hub',
    name: 'YES Bank Credit Card Offers',
    url: 'https://www.yesbank.in/credit-cards/offers',
    sourceType: 'bank_hub',
    parserModule: 'generic',
    cronSchedule: '0 15 * * MON',
    cacheTtlSeconds: 7 * 86400,
    firecrawlOptions: { onlyMainContent: true, formats: ['markdown'] },
    issuerHint: 'YES Bank',
  },

  // Aggregator (twice/week)
  {
    slug: 'desidime-cc',
    name: 'DesiDime Credit Cards',
    url: 'https://www.desidime.com/credit-cards',
    sourceType: 'aggregator',
    parserModule: 'generic',
    cronSchedule: '0 5 * * TUE,FRI',
    cacheTtlSeconds: 3 * 86400,
    firecrawlOptions: {
      onlyMainContent: true,
      formats: ['markdown'],
      includeTags: ['article', 'section', '.deal-card'],
    },
  },
]
